// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

/// @title IGuardianEscrow — the external surface of the Guardian escrow contract
/// @notice This file is a **design contract**, not shipped source. It is the
///         authority on the ABI that `src/GuardianEscrow.sol` must expose, that the
///         SC-02 test suite asserts against, and that the API's chain adapter is
///         generated from. If the implementation and this file disagree, one of them
///         is a bug — decide which before writing code.
///
/// @dev Deliberately absent from the implementation: upgradeability, pausing, fees,
///      reputation, appeals, and any bounds check on `reviewWindow`. All are recorded
///      decisions, not omissions — see spec.md § Assumptions.
///
///      Access control is inherited from OpenZeppelin `AccessControl` and is NOT
///      redeclared here (`grantRole`, `revokeRole`, `hasRole`, `DEFAULT_ADMIN_ROLE`,
///      `supportsInterface`, and the role events all come from the base contract).
interface IGuardianEscrow {
    // ------------------------------------------------------------------ types

    /// @notice Where a deal is in its life. `None` is the zero value so that a lookup
    ///         on an unknown id reads as "does not exist" with no separate check.
    ///         `Settled` is terminal and is never left.
    enum DealState {
        None,
        Open,
        Delivered,
        Disputed,
        Settled
    }

    /// @notice The five permitted verdicts — 0 / 25 / 50 / 75 / 100 percent refund.
    ///         The arbitrator picks one of these and never supplies an amount, so a
    ///         compromised key cannot invent a 37% split. `Quarter` doubles as the
    ///         inconclusive-evidence default and therefore as the `forceResolve`
    ///         outcome.
    enum Tier {
        NoRefund,
        Quarter,
        Half,
        ThreeQuarter,
        Full
    }

    struct Agent {
        address owner;   // payout address, immutable for the agent's life
        uint256 price;   // base units of the settlement token, not dollars
        bytes32 defHash; // keccak256 of the canonical agent definition
        uint32 version;  // starts at 1, +1 on every updateAgent
        bool active;     // gates NEW deals only; running deals are unaffected
    }

    struct Deal {
        uint256 agentId;
        address buyer;        // refund recipient
        address seller;       // SNAPSHOT of agent.owner at purchase — never a lookup
        uint256 amount;       // SNAPSHOT of agent.price at purchase
        bytes32 defHash;      // PINNED — the definition that actually ran
        uint32 defVersion;    // PINNED
        uint64 openedAt;      // starts DELIVERY_DEADLINE
        uint64 deliveredAt;   // 0 until delivered; starts reviewWindow
        uint64 disputedAt;    // 0 until disputed; starts DISPUTE_DEADLINE
        uint32 reviewWindow;  // per-deal seconds; NOT a constant
        DealState state;
    }

    // ----------------------------------------------------------------- events

    event AgentRegistered(
        uint256 indexed agentId, address indexed owner, uint256 price, bytes32 defHash
    );
    event AgentUpdated(uint256 indexed agentId, uint32 version, uint256 price, bytes32 defHash);
    event DealOpened(
        uint256 indexed dealId,
        uint256 indexed agentId,
        address indexed buyer,
        uint256 amount,
        bytes32 defHash,
        uint32 defVersion
    );
    event Delivered(uint256 indexed dealId, uint64 at);
    /// @notice Emitted by BOTH `accept` and `release` — the two full-payout paths.
    event Released(uint256 indexed dealId, address indexed seller, uint256 amount);
    event Disputed(uint256 indexed dealId, uint64 at);
    /// @notice Emitted by BOTH `resolve` and `forceResolve`. `verdictHash` is
    ///         `bytes32(0)` for the force path — that is how the two are told apart
    ///         off-chain.
    event Resolved(
        uint256 indexed dealId, Tier tier, uint256 toBuyer, uint256 toSeller, bytes32 verdictHash
    );
    event Reclaimed(uint256 indexed dealId, address indexed buyer, uint256 amount);
    event Withdrawn(address indexed account, uint256 amount);

    // ---------------------------------------------------------------- getters

    /// @dev All of these are generated by `public` state variables in the
    ///      implementation; they are declared here so the ABI is complete.

    function OPERATOR_ROLE() external view returns (bytes32);
    function GUARDIAN_ROLE() external view returns (bytes32);

    /// @notice 24 hours. After this, an undelivered deal is reclaimable by anyone.
    function DELIVERY_DEADLINE() external view returns (uint32);

    /// @notice 72 hours. After this, an unresolved dispute is force-settleable by anyone.
    function DISPUTE_DEADLINE() external view returns (uint32);

    /// @notice The settlement token. Fixed at deployment, immutable.
    function token() external view returns (address);

    /// @dev Auto-generated struct getters return flattened tuples, not the struct.
    function agents(uint256 agentId)
        external
        view
        returns (address owner, uint256 price, bytes32 defHash, uint32 version, bool active);

    function deals(uint256 dealId)
        external
        view
        returns (
            uint256 agentId,
            address buyer,
            address seller,
            uint256 amount,
            bytes32 defHash,
            uint32 defVersion,
            uint64 openedAt,
            uint64 deliveredAt,
            uint64 disputedAt,
            uint32 reviewWindow,
            DealState state
        );

    /// @notice The pull-payment ledger. Withdrawable funds per address.
    function balances(address account) external view returns (uint256);

    /// @notice Sum of all live (unsettled) deal amounts. Exists so solvency is
    ///         checkable on-chain — mappings cannot be iterated. Also the number the
    ///         demo UI shows as "$X currently held in escrow".
    function totalEscrowed() external view returns (uint256);

    function nextAgentId() external view returns (uint256);
    function nextDealId() external view returns (uint256);

    // --------------------------------------------------------------- registry

    /// @notice Register a purchasable agent. Operator-registered so sellers need no
    ///         wallet interaction or gas.
    /// @dev OPERATOR_ROLE. Reverts `"bad owner"` if `owner` is the zero address.
    ///      Assigns `version = 1`, `active = true`. Emits `AgentRegistered`.
    function registerAgent(address owner, uint256 price, bytes32 defHash)
        external
        returns (uint256 agentId);

    /// @notice Replace price and definition hash; increments `version`.
    /// @dev OPERATOR_ROLE. Reverts `"no agent"` if unknown. Deals already open are
    ///      unaffected — they carry their own pinned hash and version.
    ///      Emits `AgentUpdated`.
    function updateAgent(uint256 agentId, uint256 price, bytes32 defHash) external;

    /// @notice Toggle whether NEW deals may be opened. Running deals continue.
    /// @dev OPERATOR_ROLE. Reverts `"no agent"` if unknown.
    function setAgentActive(uint256 agentId, bool active) external;

    // --------------------------------------------------------------- lifecycle

    /// @notice Capture `agent.price` into escrow and open a deal.
    /// @dev OPERATOR_ROLE. Pulls tokens from `msg.sender` (the operator), NOT from the
    ///      buyer — the buyer paid by card and may hold no tokens at all. **The
    ///      operator must have approved this contract first**; without an allowance
    ///      the first purchase reverts long after deployment looked successful.
    ///
    ///      Reverts `"agent inactive"`, `"bad buyer"`. Snapshots seller, amount,
    ///      defHash, defVersion, openedAt, reviewWindow. Increments `totalEscrowed`.
    ///      Emits `DealOpened`.
    ///
    ///      `reviewWindow` is NOT validated. Passing `0` closes the complaint window
    ///      instantly — guard this backend-side.
    function openDeal(uint256 agentId, address buyer, uint32 reviewWindow)
        external
        returns (uint256 dealId);

    /// @notice Record delivery and start the review window.
    /// @dev OPERATOR_ROLE. Requires state `Open`, else `"not open"`.
    ///      Sets `deliveredAt = block.timestamp`. Emits `Delivered`.
    function markDelivered(uint256 dealId) external;

    /// @notice Buyer accepts early — seller is credited the full amount.
    /// @dev Caller must be `deal.buyer` or hold OPERATOR_ROLE, else `"not buyer"`.
    ///      Requires state `Delivered`, else `"not delivered"`. Deliberately NOT
    ///      window-gated: accepting only ever does what the lapse would have done.
    ///      Emits `Released`.
    function accept(uint256 dealId) external;

    /// @notice Settle a delivered deal whose review window has lapsed.
    /// @dev **PERMISSIONLESS ON PURPOSE.** A seller must never depend on the platform
    ///      to be paid. The caller chooses nothing and gains nothing.
    ///      Requires state `Delivered` and `now >= deliveredAt + reviewWindow`, else
    ///      `"window open"`. Emits `Released`.
    function release(uint256 dealId) external;

    /// @notice Return the full amount to the buyer when nothing was ever delivered.
    /// @dev **PERMISSIONLESS ON PURPOSE.** Requires state `Open` and
    ///      `now >= openedAt + DELIVERY_DEADLINE`, else `"too early"`.
    ///      Emits `Reclaimed`.
    function reclaim(uint256 dealId) external;

    // ----------------------------------------------------------------- dispute

    /// @notice Freeze the deal pending arbitration. Moves NO value — the funds are
    ///         already escrowed; this only stops the window from lapsing into a
    ///         release.
    /// @dev Caller must be `deal.buyer` or hold OPERATOR_ROLE, else `"not buyer"`.
    ///      Requires state `Delivered` and `now < deliveredAt + reviewWindow`, else
    ///      `"window closed"`. Sets `disputedAt`. Emits `Disputed`.
    function dispute(uint256 dealId) external;

    /// @notice Rule on a disputed deal by selecting one of the five tiers.
    /// @dev GUARDIAN_ROLE. Requires state `Disputed`, else `"not disputed"`.
    ///      Computes `toBuyer = amount * bps / 10_000` and `toSeller = amount -
    ///      toBuyer` — the subtraction is what guarantees the two sum to `amount`
    ///      exactly. Credits both balances, sets `Settled`, decrements
    ///      `totalEscrowed`. Emits `Resolved`.
    /// @param verdictHash Anchor for the off-chain verdict text. Tamper-evidence only;
    ///                    the contract never reads it.
    function resolve(uint256 dealId, Tier tier, bytes32 verdictHash) external;

    /// @notice Force-settle a dispute the arbitrator never ruled on.
    /// @dev **PERMISSIONLESS ON PURPOSE** — without it, a lost arbitrator key would
    ///      freeze disputed funds forever. Requires state `Disputed` and
    ///      `now >= disputedAt + DISPUTE_DEADLINE`, else `"too early"`.
    ///      Settles at `Tier.Quarter` with `verdictHash = bytes32(0)`, because the
    ///      product's inconclusive-evidence rule already resolves to 25% and a timeout
    ///      is the ultimate unproven case. Emits `Resolved`.
    function forceResolve(uint256 dealId) external;

    // ---------------------------------------------------------------- money out

    /// @notice Pay the caller's own balance to the caller.
    /// @dev Implemented as `withdrawFor(msg.sender)` — one implementation, so the two
    ///      entry points cannot drift.
    function withdraw() external;

    /// @notice Pay `account`'s balance **to `account`**, whoever calls.
    /// @dev **The payee is `account`, never `msg.sender`.** This function exists
    ///      because the operator drives every transaction on the user's behalf; a
    ///      `msg.sender`-only withdrawal would send every payout to the operator.
    ///
    ///      Safe to leave permissionless: a caller can only move `account`'s balance
    ///      to `account`, so there is nothing to gain beyond paying their gas.
    ///
    ///      Reverts `"nothing to withdraw"` on a zero balance. Zeroes the balance
    ///      BEFORE transferring (checks-effects-interactions). This is the **only**
    ///      function in the contract that moves tokens out. Emits `Withdrawn`.
    function withdrawFor(address account) external;
}
